### ISSUE TITLE
Add vaccine records

### ISSUE THREAD

**Issue by JordanTranchina** [JordanTranchina/final#15]
As a logged-in user, I want to add to my vaccine records

**Comment by JordanTranchina** [comment]
Need to style the form so that it looks like a card during data entry

**Comment by JordanTranchina** [comment]
@sasstitt are you still cool to take a stab at styling the form into the card tomorrow?

**Comment by sasstitt** [comment]
@JordanTranchina just did! Let me know your thoughts.

**Comment by JordanTranchina** [comment]
Looks good! Optional enhancement would be to get it closer to design spec but I'm happy to submit with this.

<img width="447" alt="Screen Shot 2021-03-10 at 9 30 39 AM" src="https://user-images.githubusercontent.com/41443492/110653914-4bf55400-8183-11eb-81ce-966259820b5b.png">
