### ISSUE TITLE
Log Out

### ISSUE THREAD

**Issue by JordanTranchina** [JordanTranchina/final#5]
As a logged-in user, I want to log out

**Comment by JordanTranchina** [comment]
Need to map the "Log Out" button in navigation to log out feature. Would be great to do the same with #4 but that's a bonus

**Comment by JordanTranchina** [comment]
<img width="1792" alt="Screen Shot 2021-03-10 at 9 31 15 AM" src="https://user-images.githubusercontent.com/41443492/110654057-6c251300-8183-11eb-9b34-c5d7ff68971d.png">

Looks like Log Out only works when clicking the top left log-out link instead of the log out button on the far left. @sasstitt is investigating this in winter-2021 slack channel

**Comment by JordanTranchina** [comment]
This looks great! Only request is to push it to all pages. This is the result of clicking log out on any of the other screens

<img width="1792" alt="Screen Shot 2021-03-11 at 10 31 23 AM" src="https://user-images.githubusercontent.com/41443492/110820776-07d28400-8255-11eb-83cd-a4920cb14cdf.png">

**Comment by robfabry** [comment]
Ah yes, good catch!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JordanTranchina** [comment]
Rob this is wrapped now right?

Jordan Tranchina
MBA Candidate | Kellogg School of Management | Class of 2022
Website | LinkedIn | Schedule Call

**Comment by robfabry** [comment]
Yup – I’ll close it
