### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by JordanTranchina** [JordanTranchina/final#9]
As a logged-in user, I want to easily navigate from one page to another

**Comment by sasstitt** [comment]
@JordanTranchina styling has been updated. Do we want the image for My Account or is that a nice to have?

**Comment by JordanTranchina** [comment]
Thank you!

It's nice to have.

Jordan Tranchina
MBA Candidate | Kellogg School of Management | Class of 2022
Website | LinkedIn | Schedule Call

**Comment by JordanTranchina** [comment]
Closing the issue for now! Thanks again @sasstitt!
